### ISSUE TITLE
cannot run - missing package version info

### ISSUE THREAD

**Issue by galicae** [ZixiangLuo1161/scGAE#1]
Hi and thanks for putting this interesting tool out. I wanted to try out scGAE on my data, however I cannot get it to run. I cannot import the layers (line 4 of `scgae.py`). Could it be that you are using a different version of the `spektral` package?

Also, transforming scGAE into a real python package (adding a setup.py file) would make it much easier to install and use.

Thank you in advance!

**Comment by ZixiangLuo1161** [comment]
Thank you for your interest! I have updated the version info.

Requirements:
tensorflow --- 2.3.0
numpy --- 1.18.1
pandas --- 1.0.1
tensorflow_probability --- 0.11.0
scikit-learn --- 0.22.1
scanpy --- 1.4.4
anndata --- 0.7.4
spektral --- 0.6.1
matplotlib --- 3.0.3

**Comment by galicae** [comment]
ah thanks, getting to these versions should do the trick.
